export * from './Contact'
export * from './Footer'
export * from './Header'
export * from './Login'
export * from './NavBar'
export * from './Profile'
export * from './SetPassword'
export * from './TestComponent'
