import { ColumnDef } from '@tanstack/react-table'
import { z } from 'zod'

export const userRightSchema = z.object({
  id: z.number(),
  name: z.string(),
  description: z.string().optional(),
})

export type UserRight = z.infer<typeof userRightSchema>

enum Rights {
  API_DEVELOPER = 'API_DEVELOPER',

  RIGHT_READ = 'RIGHT_READ',
  RIGHT_UPDATE = 'RIGHT_UPDATE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  TRANSLATION_CREATE = 'TRANSLATION_CREATE',
  TRANSLATION_READ = 'TRANSLATION_READ',
  TRANSLATION_UPDATE = 'TRANSLATION_UPDATE',
  TRANSLATION_DELETE = 'TRANSLATION_DELETE',

  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  TEAM_CREATE = 'TEAM_CREATE',
  TEAM_READ = 'TEAM_READ',
  TEAM_UPDATE = 'TEAM_UPDATE',
  TEAM_DELETE = 'TEAM_DELETE',

  TEAM_MEMBER_CREATE = 'TEAM_MEMBER_CREATE',
  TEAM_MEMBER_READ = 'TEAM_MEMBER_READ',
  TEAM_MEMBER_UPDATE = 'TEAM_MEMBER_UPDATE',
  TEAM_MEMBER_DELETE = 'TEAM_MEMBER_DELETE',

  EVALUATION_CREATE = 'EVALUATION_CREATE',
  EVALUATION_CREATE_OWN = 'EVALUATION_CREATE_OWN ',
  EVALUATION_DELETE = 'EVALUATION_DELETE',
  EVALUATION_DELETE_OWN = 'EVALUATION_DELETE_OWN',
  EVALUATION_READ = 'EVALUATION_READ',
  EVALUATION_READ_OWN = 'EVALUATION_READ_OWN',

  EVALUATION_RESPONSE_CREATE = 'EVALUATION_RESPONSE_CREATE',
  EVALUATION_RESPONSE_CREATE_OWN = 'EVALUATION_RESPONSE_CREATE_OWN',
  EVALUATION_RESPONSE_DELETE = 'EVALUATION_RESPONSE_DELETE',
  EVALUATION_RESPONSE_DELETE_OWN = 'EVALUATION_RESPONSE_DELETE_OWN',
  EVALUATION_RESPONSE_READ = 'EVALUATION_RESPONSE_READ',
  EVALUATION_RESPONSE_READ_OWN = 'EVALUATION_RESPONSE_READ_OWN',
  EVALUATION_RESPONSE_UPDATE = 'EVALUATION_RESPONSE_UPDATE',
  EVALUATION_RESPONSE_UPDATE_OWN = 'EVALUATION_RESPONSE_UPDATE_OWN',

  PERFORMANCE_COMPASS_CREATE = 'PERFORMANCE_COMPASS_CREATE',
  PERFORMANCE_COMPASS_CREATE_OWN = 'PERFORMANCE_COMPASS_CREATE_OWN',
  PERFORMANCE_COMPASS_DELETE = 'PERFORMANCE_COMPASS_DELETE',
  PERFORMANCE_COMPASS_DELETE_OWN = 'PERFORMANCE_COMPASS_DELETE_OWN',
  PERFORMANCE_COMPASS_READ = 'PERFORMANCE_COMPASS_READ',
  PERFORMANCE_COMPASS_READ_OWN = 'PERFORMANCE_COMPASS_READ_OWN',
  PERFORMANCE_COMPASS_UPDATE = 'PERFORMANCE_COMPASS_UPDATE',
  PERFORMANCE_COMPASS_UPDATE_OWN = 'PERFORMANCE_COMPASS_UPDATE_OWN',

  DISCUSSION_CREATE = 'DISCUSSION_CREATE',
  DISCUSSION_CREATE_OWN = 'DISCUSSION_CREATE_OWN',
  DISCUSSION_DELETE = 'DISCUSSION_DELETE',
  DISCUSSION_DELETE_OWN = 'DISCUSSION_DELETE_OWN',
  DISCUSSION_READ = 'DISCUSSION_READ',
  DISCUSSION_READ_OWN = 'DISCUSSION_READ_OWN',
  DISCUSSION_UPDATE = 'DISCUSSION_UPDATE',
  DISCUSSION_UPDATE_OWN = 'DISCUSSION_UPDATE_OWN',
}

export type UserTableProps = {
  rights: UserRight[]
  columns: ColumnDef<UserRight>[]
}
